import:
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-vms-deb-r4.0.yml
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-vms-rpm-r4.0.yml
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-base-r4.0.yml
  - source: QubesOS/qubes-continuous-integration:R4.0/travis-dom0-r4.0.yml

env:
  global:
    - TRAVIS_INSTALL_EXCLUDE=".*"
